In [1]:
import pandas as pd

In [3]:
# deaths = pd.read_csv("deaths.csv")
confirmed = pd.read_csv("conf.csv")
# recovered = pd.read_csv("recovered.csv")

In [4]:
confirmed

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/7/20,3/8/20,3/9/20,3/10/20,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20
0,NaN,Thailand,15.0000,101.0000,2,3,5,7,8,8,...,50,50,50,53,59,70,75,82,114,147
1,NaN,Japan,36.0000,138.0000,2,1,2,2,4,4,...,461,502,511,581,639,639,701,773,839,825
2,NaN,Singapore,1.2833,103.8333,0,1,3,3,4,5,...,138,150,150,160,178,178,200,212,226,243
3,NaN,Nepal,28.1667,84.2500,0,0,0,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,NaN,Malaysia,2.5000,112.5000,0,0,0,3,4,4,...,93,99,117,129,149,149,197,238,428,566
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458,NaN,Somalia,5.1521,46.1996,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
459,NaN,Tanzania,-6.3690,34.8888,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
460,NaN,The Bahamas,24.2500,-76.0000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
461,Virgin Islands,US,18.3358,-64.8963,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1
462,Cayman Islands,United Kingdom,19.3133,-81.2546,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1

In [5]:
def formatize(table):
    del table["Lat"]
    del table["Long"]
    del table["Province/State"]
    return table.groupby("Country/Region").sum()

In [6]:
fd = formatize(confirmed)

In [7]:
confy = confirmed.groupby("Country/Region").sum()

In [8]:
confy

,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,3/7/20,3/8/20,3/9/20,3/10/20,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20
Country/Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,0,0,0,0,0,...,1,4,4,5,7,7,7,11,16,21
Albania,0,0,0,0,0,0,0,0,0,0,...,0,0,2,10,12,23,33,38,42,51
Algeria,0,0,0,0,0,0,0,0,0,0,...,17,19,20,20,20,24,26,37,48,54
Andorra,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,2
Antigua and Barbuda,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uruguay,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4,4,8
Uzbekistan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,6
Venezuela,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,10,17
Vietnam,0,2,2,2,2,2,2,2,2,2,...,18,30,30,31,38,39,47,53,56,61
occupied Palestinian territory,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
import json
with open('conf.json','w') as f:
    f.write(confy.to_json())

In [63]:
pip install moment

Collecting moment
  Using cached https://files.pythonhosted.org/packages/83/58/bcd2d9bdb9eca1d7e90a61a8e4c515b76255e0240db2d7653ba99428300b/moment-0.8.2.tar.gz
Collecting dateparser>=0.6 (from moment)
  Using cached https://files.pythonhosted.org/packages/ad/0c/aba72d8454c28ab3800f3efd1ab3fe4f3fa41eb2746adc0cdcb318200796/dateparser-0.7.4-py2.py3-none-any.whl
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/site-packages (from moment) (2019.3)
Collecting times (from moment)
  Using cached https://files.pythonhosted.org/packages/5d/2f/811d8183abae998effbbb1a191af2469a6c18bfcb4d3edfd4fe9c096c5f8/times-0.7-py2.py3-none-any.whl
Collecting regex!=2019.02.19 (from dateparser>=0.6->moment)
  Using cached https://files.pythonhosted.org/packages/e8/76/8ac7f467617b9cfbafcef3c76df6f22b15de654a62bea719792b00a83195/regex-2020.2.20.tar.gz
Collecting tzlocal (from dateparser>=0.6->moment)
  Using cached https://files.pythonhosted.org/packages/ef/99/53bd1ac9349262f59c1c421d8fcc2559ae8a5eeffed9202684756b648d33/tzlocal-2.0.0-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/site-packages (from dateparser>=0.6->moment) (2.8.0)
Collecting arrow (from times->moment)
  Using cached https://files.pythonhosted.org/packages/92/fa/f84896dede5decf284e6922134bf03fd26c90870bbf8015f4e8ee2a07bcc/arrow-0.15.5-py2.py3-none-any.whl
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/site-packages (from python-dateutil->dateparser>=0.6->moment) (1.12.0)
Building wheels for collected packages: moment, regex
  Building wheel for moment (setup.py) ... done
  Stored in directory: /Users/iashris/Library/Caches/pip/wheels/a3/34/33/a815da729a0a46eb92201ef672b921e5d5a31fa7370fa3d5ba
  Building wheel for regex (setup.py) ... done
  Stored in directory: /Users/iashris/Library/Caches/pip/wheels/22/4a/99/3a20d265a6c7a186cc9903a4d45e29d0c8323c344e307b161e
Successfully built moment regex
Installing collected packages: regex, tzlocal, dateparser, arrow, times, moment
Successfully installed arrow-0.15.5 dateparser-0.7.4 moment-0.8.2 regex-2020.2.20 times-0.7 tzlocal-2.0.0
Note: you may need to restart the kernel to use updated packages.

In [9]:
del confy["Lat"]

KeyError: 'Lat'

In [65]:
del confy["Long"]

In [11]:
import moment

In [12]:
(moment.date("1/22/20")-moment.date("1/24/20")).days

-2

In [13]:
confy.columns = map(lambda x: (moment.date(x)-moment.date("1/22/20")).days, confy.columns)

In [14]:
confy

,0,1,2,3,4,5,6,7,8,9,...,45,46,47,48,49,50,51,52,53,54
Country/Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,0,0,0,0,0,...,1,4,4,5,7,7,7,11,16,21
Albania,0,0,0,0,0,0,0,0,0,0,...,0,0,2,10,12,23,33,38,42,51
Algeria,0,0,0,0,0,0,0,0,0,0,...,17,19,20,20,20,24,26,37,48,54
Andorra,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,2
Antigua and Barbuda,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uruguay,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4,4,8
Uzbekistan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,6
Venezuela,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,10,17
Vietnam,0,2,2,2,2,2,2,2,2,2,...,18,30,30,31,38,39,47,53,56,61
occupied Palestinian territory,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
confy.index.values

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahrain', 'Bangladesh',
       'Belarus', 'Belgium', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Brazil', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chile', 'China', 'Colombia',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cruise Ship', 'Cuba', 'Cyprus',
       'Czechia', 'Denmark', 'Dominican Republic', 'Ecuador', 'Egypt',
       'Equatorial Guinea', 'Estonia', 'Eswatini', 'Ethiopia', 'Finland',
       'France', 'French Guiana', 'Gabon', 'Georgia', 'Germany', 'Ghana',
       'Greece', 'Greenland', 'Guadeloupe', 'Guam', 'Guatemala',
       'Guernsey', 'Guinea', 'Guyana', 'Holy See', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan',
       'Kazakhstan', 'Kenya', 'Korea, South', 'Kosovo', 'Kuwait',
       'Latvia', 'Lebanon', 'Liberia', 'Liechtenstein', 'Lithuania',
       'Luxembourg', 'Malaysia', 'Maldives', 'Malta', 'Martinique',
       'Mauritania', 'Mayotte', 'Mexico', 'Moldova', 'Monaco', 'Mongolia',
       'Morocco', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand',
       'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan',
       'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
       'Puerto Rico', 'Qatar', 'Republic of the Congo', 'Reunion',
       'Romania', 'Russia', 'Rwanda', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'San Marino', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Singapore', 'Slovakia',
       'Slovenia', 'Somalia', 'South Africa', 'Spain', 'Sri Lanka',
       'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Taiwan*',
       'Tanzania', 'Thailand', 'The Bahamas', 'Togo',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'US', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'Uruguay', 'Uzbekistan',
       'Venezuela', 'Vietnam', 'occupied Palestinian territory'],
      dtype=object)

In [122]:
for row in confy.iterrows():
    print(row[0],drow(row[1]))

Afghanistan 1.0
Albania 2.125
Algeria 0.8333333333333334
Andorra 0.0
Argentina 1.4133333333333336
Armenia 0.0
Australia 1.5734751359751358
Austria 1.3360372633902045
Azerbaijan 0.0
Bahrain 1.8033333333333335
Bangladesh 0.0
Belarus 0.0
Belgium 1.8906719000376735
Bhutan 0.0
Bolivia 0
Bosnia and Herzegovina 0.3333333333333333
Brazil 0.5134920634920634
Brunei 0.0
Bulgaria 0.0
Burkina Faso 1.0
Cambodia 0.0
Cameroon 0.0
Canada 2.676709401709402
Chile 0.5
China 0.892608937720995
Colombia 1.5
Congo (Kinshasa) 0
Costa Rica 0.3333333333333333
Cote d'Ivoire 0
Croatia 0.6875
Cruise Ship 0.0
Cuba 0
Cyprus 1.75
Czechia 2.6875
Denmark 1.425569198243617
Dominican Republic 0.0
Ecuador 0.8333333333333334
Egypt 2.18218954248366
Estonia 2.25
Finland 1.1005102040816328
France 2.1412899101476186
French Guiana 0.0
Georgia 0.05555555555555555
Germany 2.6459312232209675
Greece 4.916599025974026
Guyana 0
Holy See 0.0
Honduras 0
Hungary 0.5416666666666666
Iceland 1.1432323232323234
India 1.2206452062430324
Indonesia 1.598076923076923
Iran 1.2496910349231485
Iraq 0.7502645502645504
Ireland 1.8846153846153846
Israel 1.5101426024955438
Italy 1.3209549243095948
Jamaica 0
Japan 1.639940940396321
Jordan 0.0
Korea, South 1.3732103506317603
Kuwait 0.26666666666666666
Latvia 1.375
Lebanon 1.1031746031746033
Liechtenstein 0.0
Lithuania 0.0
Luxembourg 0.25
Malaysia 1.1373737373737371
Maldives 0.5
Malta 0.25
Martinique 0.0
Mexico 0.6666666666666667
Moldova 0.0
Monaco 0.0
Mongolia 0.0
Morocco 0.6666666666666666
Nepal 0
Netherlands 1.4963173800000726
New Zealand 0.25
Nigeria 0.0
North Macedonia 0.0
Norway 1.8040853090283013
Oman 0.16666666666666666
Pakistan 0.075
Panama 7.0
Paraguay 0.0
Peru 1.05
Philippines 1.906153846153846
Poland 0.7066666666666667
Portugal 1.018800247371676
Qatar 6.335034013605442
Reunion 0
Romania 0.9166666666666666
Russia 1.8
San Marino 1.621768707482993
Saudi Arabia 0.42333333333333334
Senegal 1.0
Serbia 0.875
Singapore 0.8574413241079908
Slovakia 0.25
Slovenia 1.0583333333333333
South Africa 0.5
Spain 1.5755360828943825
Sri Lanka 0
Sweden 2.5129125657242244
Switzerland 1.6084873316586872
Taiwan* 0.7125
Thailand 0.75
Togo 0.0
Tunisia 0.2222222222222222
Turkey 0
US 2.09413934641
Ukraine 0.0
United Arab Emirates 0.05555555555555555
United Kingdom 1.6084767953894168
Vietnam 4.333333333333333

In [121]:
import copy
def drow(LL):
    L=copy.deepcopy(LL[-15:-1])
    Z = [y - x for x,y in zip(L,L[1:])]
    V = [y / x for x,y in zip(Z,Z[1:]) if x!=0]
    if len(V)>0:
        return sum(V)/len(V)
    else:
        return 0

In [107]:
drow([1,2,3,30,60,120,240,480])

[1.0, 27.0, 1.1111111111111112, 2.0, 2.0, 2.0]

In [42]:
a=['Afghanistan', 'Albania', 'Algeria', 'Andorra',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahrain', 'Bangladesh',
       'Belarus', 'Belgium', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Brazil', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chile', 'China', 'Colombia',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cruise Ship', 'Cuba', 'Cyprus',
       'Czechia', 'Denmark', 'Dominican Republic', 'Ecuador', 'Egypt',
       'Equatorial Guinea', 'Estonia', 'Eswatini', 'Ethiopia', 'Finland',
       'France', 'French Guiana', 'Gabon', 'Georgia', 'Germany', 'Ghana',
       'Greece', 'Greenland', 'Guadeloupe', 'Guam', 'Guatemala',
       'Guernsey', 'Guinea', 'Guyana', 'Holy See', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan',
       'Kazakhstan', 'Kenya', 'Korea, South', 'Kosovo', 'Kuwait',
       'Latvia', 'Lebanon', 'Liberia', 'Liechtenstein', 'Lithuania',
       'Luxembourg', 'Malaysia', 'Maldives', 'Malta', 'Martinique',
       'Mauritania', 'Mayotte', 'Mexico', 'Moldova', 'Monaco', 'Mongolia',
       'Morocco', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand',
       'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan',
       'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
       'Puerto Rico', 'Qatar', 'Republic of the Congo', 'Reunion',
       'Romania', 'Russia', 'Rwanda', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'San Marino', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Singapore', 'Slovakia',
       'Slovenia', 'Somalia', 'South Africa', 'Spain', 'Sri Lanka',
       'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Taiwan',
       'Tanzania', 'Thailand', 'The Bahamas', 'Togo',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'US', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'Uruguay', 'Uzbekistan',
       'Venezuela', 'Vietnam', 'occupied Palestinian territory']
# in dataset

In [48]:
b = ['Afghanistan',
 'Albania',
 'Algeria',
 'Angola',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bangladesh',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominican Republic',
 'East Timor',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Falkland Islands',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'French Southern and Antarctic Lands',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Greenland',
 'Guatemala',
 'Guinea',
 'Guinea Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Mali',
 'Malta',
 'Mauritania',
 'Mexico',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'Northern Cyprus',
 'Northern Cyprus',
 'Norway',
 'Oman',
 'Pakistan',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Republic of Serbia',
 'Republic of the Congo',
 'Romania',
 'Russia',
 'Rwanda',
 'Saudi Arabia',
 'Senegal',
 'Sierra Leone',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'Somaliland',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Thailand',
 'The Bahamas',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United Republic of Tanzania',
 'United States of America',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'West Bank',
 'Western Sahara',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [51]:
inb = [x for x in b if x not in a]

In [52]:
inb

['Angola',
 'Belize',
 'Bermuda',
 'Botswana',
 'Burundi',
 'Chad',
 'Czech Republic',
 'Democratic Republic of the Congo',
 'Djibouti',
 'East Timor',
 'El Salvador',
 'Eritrea',
 'Falkland Islands',
 'Fiji',
 'French Southern and Antarctic Lands',
 'Gambia',
 'Guinea Bissau',
 'Haiti',
 'Ivory Coast',
 'Kyrgyzstan',
 'Laos',
 'Lesotho',
 'Libya',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Mali',
 'Montenegro',
 'Mozambique',
 'Myanmar',
 'New Caledonia',
 'Nicaragua',
 'Niger',
 'North Korea',
 'Northern Cyprus',
 'Northern Cyprus',
 'Papua New Guinea',
 'Republic of Serbia',
 'Sierra Leone',
 'Solomon Islands',
 'Somaliland',
 'South Korea',
 'South Sudan',
 'Swaziland',
 'Syria',
 'Tajikistan',
 'Turkmenistan',
 'Uganda',
 'United Republic of Tanzania',
 'United States of America',
 'Vanuatu',
 'West Bank',
 'Western Sahara',
 'Yemen',
 'Zambia',
 'Zimbabwe']